name: analytics
imagename: analytics
namespace: lottery


service:
  type: ClusterIP
  multiport: 
  - name: analytics
    port: 8080


deployment:
  replicas: 1
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: analytics
    imagename: analytics
    port: 8080
    probe:
      livenessProbe:
        enable: true
        initialDelaySeconds: 120
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 10
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    restartPolicy: Always
    env:
      JAVA_TOOL_OPTIONS: '-Xmx1536m -XX:ParallelGCThreads=2 -XX:CICompilerCount=2'
    envFromSecret:
      JWT_KEY:
        lottery-jwt: private-key
    # BIGQUERY_PRIVATE-KEY:
    #   bigquery-secret: bigquery-key

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: mytestingress
    paths:
      - path: /
        pathType: Prefix

hpa:
  enable: false