name: purchase-service
imagename: purchase
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 15
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      platform-service-ssl: ssl
    DATASOURCE_BELLOTO_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_BELLOTO_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_BELLOTO_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELLOTO_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    KAFKA_ADDRESS:
      kafka-bbsoft-main-preprod-write: host
    PAYMENT_PURCHASE_BEPAID_ID:
      platform-secret: shop_id
    PAYMENT_PURCHASE_BEPAID_KEY:
      platform-secret: bepaid_key


ingress:
  enable: false


hpa:
  enable: false