name: notification
imagename: notification
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  podAntiAffinity: true
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 15
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      platform-service-ssl: ssl
    KAFKA_ADDRESS:
      kafka-bbsoft-main-preprod-write: host
    DATASOURCE_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    SMS_MTS_TOLOTO_SEND-URL:
      notification-mts: url
    SMS_MTS_TOLOTO_USERNAME:
      notification-mts: user
    SMS_MTS_TOLOTO_PASSWORD:
      notification-mts: pass
    SMS_MTS_TOLOTO_ALPHA-NAME:
      notification-mts: alpha-name


ingress:
  enable: false


hpa:
  enable: false