name: dwh-service
imagename: dwh
namespace: lottery


service:
  type: ClusterIP
  multiport: 
  - name: dwh-service
    port: 8080


deployment:
  replicas: 1
  monitoring:
    enable: true
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: dwh-service
    imagename: dwh
    port: 8080
    probe:
      livenessProbe:
        enable: true
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 10
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    restartPolicy: Always
    env: {}

    envFromSecret:
      DATASOURCE_PORT:
        postgres-lottery-main-write: port
      DATASOURCE_USERNAME:
        postgres-lottery-main-admin: superuser
      JWT_KEY:
        lottery-jwt: private-key
      DATASOURCE_PASSWORD:
        postgres-lottery-main-admin: superuser-password
      KAFKA_ADDRESS:
        kafka-lottery-main-write: address
      DATASOURCE_ADDRESS:
        postgres-lottery-main-write: host

ingress:
  enable: false


hpa:
  enable: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60