name: notification
imagename: notification
namespace: default


service:
  type: ClusterIP
  multiport: 
  - name: notification
    port: 8080


deployment:
  replicas: 1
  podAntiAffinity: true
  imagePullSecrets:
    - gcr-json-key
  containers:
  - name: notification
    imagename: notification
    port: 8080
    probe:
      livenessProbe:
        enable: true
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 15
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    restartPolicy: Always
    env: {}
    envFromSecret:
      JWT_KEY:
        jwt-qa: jwt-key
      KAFKA_ADDRESS:
        kafka-default-qa-write: host
      DATASOURCE_ADDRESS:
        postgres-default-qa-write: host
      DATASOURCE_PORT:
        postgres-default-qa-write: port
      DATASOURCE_USERNAME:
        postgres-default-qa-admin: superuser
      DATASOURCE_PASSWORD:
        postgres-default-qa-admin: superuser-password

ingress:
  enable: false


hpa:
  enable: false