name: dwh-service
imagename: dwh
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  podAntiAffinity: true
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "500m"
      memory: 1Gi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      dwh-service-key: jwt-key
    KAFKA_ADDRESS:
      kafka-bbsoft-main-preprod-write: host
    DATASOURCE_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password


ingress:
  enable: false


hpa:
  enable: false