name: backoffice-ui
imagename: backoffice-ui
namespace: bbsoft


service:
  type: ClusterIP
  port: 3000

  ########################### not ready #################
deployment:
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      initialDelaySeconds: 15
      probeType: tcp
      tcp:
        port: 3000
    readinessProbe:
      enable: true
      initialDelaySeconds: 15
      probeType: tcp
      tcp:
        port: 3000
  resources:
    requests:
      cpu: "300m"
      memory: 512Mi
      ephemeral_storage: 512Mi
    limits:
      cpu: "500m"
      ephemeral_storage: 1Gi
      memory: 1Gi
  restartPolicy: Always
  env: {}

ingress:
  enable: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 3m
  hosts:
  - host: preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix

hpa:
  enable: false