name: sequence-hash-verifier
imagename: sequence
namespace: lottery


service:
  type: ClusterIP
  multiport: 
  - name: sequence-hash-verifier
    port: 8080


deployment:
  replicas: 1
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: sequence-hash-verifier
    imagename: sequence
    port: 8080
    probe:
      livenessProbe:
        enable: true
        initialDelaySeconds: 120
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 30
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: "1"
        memory: 10000Mi
        ephemeral_storage: 10000Mi
      limits:
        cpu: "1"
        memory: 30000Mi
        ephemeral_storage: 30000Mi
    restartPolicy: Always
    env: {}

    envFromSecret:
      DATASOURCE_BELLOTO-READ_ADDRESS:
        postgres-lottery-main-write: host
      DATASOURCE_BELLOTO_PORT:
        postgres-lottery-main-write: port
      DATASOURCE_BELLOTO-WRITE_ADDRESS:
        postgres-lottery-main-write: host
      DATASOURCE_BELLOTO-WRITE_USERNAME:
        postgres-lottery-main-admin: superuser
      DATASOURCE_BELLOTO_ADDRESS:
        postgres-lottery-main-write: host
      DATASOURCE_BELLOTO-WRITE_PORT:
        postgres-lottery-main-write: port
      DATASOURCE_BELLOTO-WRITE_PASSWORD:
        postgres-lottery-main-admin: superuser-password
      DATASOURCE_BELLOTO-READ_PASSWORD:
        postgres-lottery-main-admin: superuser-password
      DATASOURCE_ARCHIVE_ADDRESS:
        postgres-lottery-main-write: host
      DATASOURCE_ARCHIVE_PORT:
        postgres-lottery-main-write: port
      DATASOURCE_BELLOTO-READ_PORT:
        postgres-lottery-main-write: port
      DATASOURCE_BELLOTO_USERNAME:
        postgres-lottery-main-admin: superuser
      DATASOURCE_BELLOTO-READ_USERNAME:
        postgres-lottery-main-admin: superuser
      DATASOURCE_ARCHIVE_USERNAME:
        postgres-lottery-main-admin: superuser
      DATASOURCE_BELLOTO_PASSWORD:
        postgres-lottery-main-admin: superuser-password
      DATASOURCE_ARCHIVE_PASSWORD:
        postgres-lottery-main-admin: superuser-password

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: sequence-hash-verifier-preprod.belbet.by
    paths:
      - path: /
        pathType: ImplementationSpecific


hpa:
  enable: false