{{- if .Values.ingress.enable }}
{{- $svcName := .Values.name -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
   {{- range $key, $value := .Values.ingress.annotations -}}
        {{- $key | nindent 4 }}: {{ $value | quote }}
      {{- end }}
  name: {{ .Values.name -}}-ingress
  labels:
    app: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - backend:
          service:
            name: {{ $svcName -}}-svc
            port:
              number: {{ $svcPort }}
        path: {{ .path }}
        pathType: {{ .pathType }}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}