apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}-svc
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- range .Values.service.multiport }}
  - port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
    name: {{ .name }}
  {{- end }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}