apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}-svc
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.name }}
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}