name: backoffice
imagename: backoffice
namespace: lottery


service:
  type: ClusterIP
  multiport: 
  - name: backoffice
    port: 8080

deployment:
  replicas: 1
  monitoring:
    enable: true
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: backoffice
    imagename: backoffice
    port: 8080
    probe:
      livenessProbe:
        enable: true
        initialDelaySeconds: 300
        probeType: http
        http:
          path: /actuator/health/liveness
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 15
        probeType: http
        http:
          path: /actuator/health/readiness
          port: 8080
    resources:
      requests:
        cpu: 1
        memory: 2Gi
        ephemeral_storage: 6Gi
      limits:
        cpu: 1
        ephemeral_storage: 8Gi
        memory: 6Gi
    restartPolicy: Always
    env: {}
    envFromSecret: {}
    

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-max-body-size: 8192m
    nginx.ingress.kubernetes.io/proxy-body-size: 3584m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "2500"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "2500"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/server-snippet: if ($request_uri = /actuator/prometheus) { return 403; }
  hosts:
  - host: bo-preprod.belbet.by
    paths:
      - path: /
        pathType: ImplementationSpecific


hpa:
  enable: false
