name: application
imagename: application
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  podAntiAffinity: true
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      initialDelaySeconds: 300
      probeType: http
      http:
        path: /actuator/health/liveness
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health/readiness
        port: 8080
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 3Gi
  restartPolicy: Always
  env: {}
  envFromSecret:
    PAYMENT_PURCHASE_BEPAID_ID:
      platform-secret: shop_id
    PAYMENT_PURCHASE_BEPAID_KEY:
      platform-secret: bepaid_key
    JWT_KEY:
      platform-service-ssl: ssl
    DATASOURCE_BELLOTO_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_BELLOTO_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_BELLOTO_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELLOTO_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    DATASOURCE_BELLOTO-REPORT_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_BELLOTO-REPORT_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_BELLOTO-REPORT_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELLOTO-REPORT_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    KAFKA_ADDRESS:
      kafka-bbsoft-main-preprod-write: host
    DATASOURCE_CLICKHOUSE_ADDRESS:
      clickhouse-default-preprod-credentials: host
    DATASOURCE_CLICKHOUSE_USER:
      clickhouse-default-preprod-credentials: pwd-lottery-readonly
    DATASOURCE_CLICKHOUSE_PASSWORD:
      clickhouse-default-preprod-credentials: pwd-lottery-readonly

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: game-api-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false
