name: dwh-service
imagename: dwh
namespace: default



service:
  type: ClusterIP
  multiport: 
  - name: dwh-service
    port: 8080


deployment:
  replicas: 1
  podAntiAffinity: true
  imagePullSecrets:
    - gcr-json-key
  containers:
  - name: dwh-service
    imagename: dwh
    port: 8080
    probe:
      livenessProbe:
        enable: true
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 10
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "500m"
        memory: 1Gi
    restartPolicy: Always
    env: {}
    envFromSecret:
      JWT_KEY:
        jwt-qa: jwt-key
      KAFKA_ADDRESS:
        kafka-default-qa-write: host
      DATASOURCE_ADDRESS:
        postgres-default-qa-write: host
      DATASOURCE_PORT:
        postgres-default-qa-write: port
      DATASOURCE_USERNAME:
        postgres-default-qa-admin: superuser
      DATASOURCE_PASSWORD:
        postgres-default-qa-admin: superuser-password


ingress:
  enable: false


hpa:
  enable: false