name: api-gateway
imagename: api-gateway
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  podAntiAffinity: true
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health/liveness
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health/readiness
        port: 8080
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      ephemeral_storage: 1Gi
    limits:
      cpu: 1
      ephemeral_storage: 2560Mi
      memory: 2560Mi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      platform-service-ssl: ssl
    DATASOURCE_BELLOTO_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_BELLOTO_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_BELLOTO_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELLOTO_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    KAFKA_ADDRESS:
      kafka-bbsoft-main-preprod-write: host

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: 'real_ip_header X-Forwarded-For; real_ip_recursive on;'
  hosts:
  - host: apigateway-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false