name: analytics
imagename: analytics
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  restartPolicy: Always
  env:
    JAVA_TOOL_OPTIONS: '-Xmx1536m -XX:ParallelGCThreads=2 -XX:CICompilerCount=2'
    SERVER_PORT: '8080'
    BIGQUERY_PROJECT-ID: 'bbsoft-dev'
    BIGQUERY_EVENT-TABLE-NAME: 'client_events_dev'
    BIGQUERY_PRIVATE-KEY-ID: '685ee3b59beface75771b548e42f68318e78ba95'
    BIGQUERY_CLIENT-EMAIL: 'dev-bigquery-writer@bbsoft-dev.iam.gserviceaccount.com'
    BIGQUERY_CLIENT-ID: '117865014381877489287'
    BIGQUERY_AUTH-URI: 'https://accounts.google.com/o/oauth2/auth'
    BIGQUERY_TOKEN-URI: 'https://oauth2.googleapis.com/token'
    BIGQUERY_AUTH-PROVIDER-X509-CERT-URL: 'https://www.googleapis.com/oauth2/v1/certs'
    BIGQUERY_CLIENT-X509-CERT-URL: 'https://www.googleapis.com/robot/v1/metadata/x509/dev-bigquery-writer%40bbsoft-dev.iam.gserviceaccount.com'
    JWT_ACCESS-TOKEN-TIMEOUT: '1h'
    SPRING_REDIS_HOST: 'redis-bbsoft-main-preprod'
  envFromSecret:
    JWT_KEY:
      analytics-keys: jwt-key
    BIGQUERY_PRIVATE-KEY:
      analytics-keys: bigquery-key

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: analytics-api-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false