name: gatekeeper
imagename: gatekeeper
namespace: lottery


service:
  type: ClusterIP
  multiport: 
  - name: gatekeeper
    port: 8080


deployment:
  replicas: 1
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: gatekeeper
    imagename: gatekeeper
    port: 8080
    probe:
      livenessProbe:
        enable: true
        initialDelaySeconds: 120
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 30
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: "500m"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    restartPolicy: Always
    env:
      DATASOURCE_GATEKEEPER_POOL-NAME: application-gatekeeper
      DATASOURCE_GATEKEEPER_MIN-IDLE: "10"
      DATASOURCE_GATEKEEPER_MAX-POOL-SIZE: "30"
      DATASOURCE_GATEKEEPER_CONNECTION-TIMEOUT: "10000"
    envFromSecret:
      DATASOURCE_GATEKEEPER_USERNAME:
        postgres-lottery-gatekeeper-write: user
      DATASOURCE_GATEKEEPER_PASSWORD:
        postgres-lottery-gatekeeper-write: password
      DATASOURCE_GATEKEEPER_URL:
        gatekeeper-db: url


ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 3584m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "2500"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "2500"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3200"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - host: gatekeeper-loto-preprod.belbet.by
    paths:
      - path: /
        pathType: Prefix
  tls:
    - hosts:
      - gatekeeper-loto-preprod.belbet.by
      secretName: default-ssl-secret


hpa:
  enable: false
