name: unity-games
imagename: unity-games
namespace: bbsoft
service:
  type: ClusterIP
  port: 3000
deployment:
  replica: 1
  livenessProbe: true
  readinessProbe: true
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral_storage: 512Mi
    limits:
      cpu: "1"
      ephemeral_storage: 1Gi
      memory: 2Gi
  restartPolicy: Always
ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: unity-games-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix
hpa:
  enable: false