name: platform-service
imagename: platform
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      platform-service-ssl: ssl
    EXTERNAL_TOLOTO_JWT_SECRET:
      platform-service-key: toloto-jwt
    DATASOURCE_PLATFORM_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_PLATFORM_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_PLATFORM_USERNAME:
      postgres-bbsoft-main-preprod-write: user
    DATASOURCE_PLATFORM_PASSWORD:
      postgres-bbsoft-main-preprod-write: password
    DATASOURCE_BELBET_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELBET_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    KAFKA_HOST:
      kafka-lottery: host
    PAYMENT_PURCHASE_BEPAID_ID:
      platform-secret: shop_id
    PAYMENT_PURCHASE_BEPAID_KEY:
      platform-secret: bepaid_key


ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: platform-service-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false