name: platform-service
imagename: platform
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 10
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  restartPolicy: Always
  env:
    BASE_SERVICE_URL: 'http://application-svc:8080'
    DATASOURCE_PLATFORM_DATABASE: 'bbsoft'
    TOLOTO_PAPERLOTTERY_SERVICE_URL: 'http://toloto.lottery.svc.cluster.local:8080'
    TOLOTO_ACTIVELOTTERY_SERVICE_URL: 'http://active-lottery.lottery.svc.cluster.local:8080'
    TOLOTO_PAPER_LOTTERY_API_SECRET: 'IQC3Ji&Ec#DVtGZtQ@sNSAtryQoLi*u1'
    BALANCE_SERVICE_URL: 'http://application-svc:8080'
    BELBET_LOTTERY_SERVICE_URL: 'http://application-svc:8080'
    PURCHASE_SERVICE_URL: 'http://purchase-service-svc:8080'
    WITHDRAW_SERVICE_URL: 'http://application-svc:8080'
    JWT_ACCESS-TOKEN-TIMEOUT: '5m'
    JWT_INACTIVITY-TIMEOUT: '15m'
    EXTERNAL_TOLOTO_JWT_EXPIRATION: '480m'
    EXTERNAL_TOLOTO_JWT_REFRESH_SESSION_EXPIRATION: '500m'
  envFromSecret:
    JWT_KEY:
      platform-service-ssl: ssl
    EXTERNAL_TOLOTO_JWT_SECRET:
      platform-service-key: toloto-jwt
    DATASOURCE_PLATFORM_ADDRESS:
      postgres-bbsoft-main-preprod-write: host
    DATASOURCE_PLATFORM_PORT:
      postgres-bbsoft-main-preprod-write: port
    DATASOURCE_PLATFORM_USERNAME:
      postgres-bbsoft-main-preprod-write: user
    DATASOURCE_PLATFORM_PASSWORD:
      postgres-bbsoft-main-preprod-write: password
    DATASOURCE_BELBET_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    DATASOURCE_BELBET_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password
    KAFKA_HOST:
      kafka-bbsoft-main-preprod-write-for-platform-service: host


ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: platform-service-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false