name: purchase-service
imagename: purchase
namespace: test1


service:
  type: ClusterIP
  multiport: 
  - name: purchase
    port: 8080


deployment:
  replicas: 2
  monitoring:
    enable: true
  imagePullSecrets:
    - docker-registry-preprod
  containers:
  - name: purchase
    imagename: purchase
    port: 8080
    probe:
      livenessProbe:
        enable: true
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 15
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    restartPolicy: Always
    env: {}
    envFromSecret:

ingress:
  enable: false


hpa:
  enable: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
