name: chat-bot
imagename: chat-bot
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  podAntiAffinity: true
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      initialDelaySeconds: 120
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 30
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: "500m"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2548Mi
  restartPolicy: Always
  env: {}
  envFromSecret:
    JWT_KEY:
      chat-bot-key: jwt-key
    SPRING_DATASOURCE_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    SPRING_DATASOURCE_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password


ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: chat-bot-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false