name: chat-bot
imagename: chat-bot
namespace: bbsoft


service:
  type: ClusterIP
  port: 8080


deployment:
  replica: 1
  podAntiAffinity: true
  imagePullSecrets:
    - docker-registry-secret
  probe:
    livenessProbe:
      enable: true
      initialDelaySeconds: 120
      probeType: http
      http:
        path: /actuator/health
        port: 8080
    readinessProbe:
      enable: true
      initialDelaySeconds: 30
      probeType: http
      http:
        path: /actuator/health
        port: 8080
  resources:
    requests:
      cpu: "500m"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2548Mi
  restartPolicy: Always
  env:
    JAVA_TOOL_OPTIONS: '-Xmx1024m -XX:ParallelGCThreads=2 -XX:CICompilerCount=2'
    JWT_ACCESS-TOKEN-TIMEOUT: '30s'
    SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-bbsoft-main-preprod-master.bbsoft.svc.cluster.local/chat_bot'
    CHAT-BOT_TELEGRAM_TOKEN: '5379792548:AAEceVjRNJUHoOM7YlG-vbzMCxpYvyIvqjk'
    CHAT-BOT_TELEGRAM_NAME: 'bet_qa_bot'
    CHAT-BOT_VIBER_TOKEN: '4a631d355567d271-5a9f0710f42b6e39-7dfc85322a71cf5'
    CHAT-BOT_VIBER_NAME: 'betqabot'
    LOTTERY_API_URL: 'https://apigateway-preprod.belbet.by/api/v2/chat-bot'
  envFromSecret:
    JWT_KEY:
      chat-bot-key: jwt-key
    SPRING_DATASOURCE_USERNAME:
      postgres-bbsoft-main-preprod-admin: superuser
    SPRING_DATASOURCE_PASSWORD:
      postgres-bbsoft-main-preprod-admin: superuser-password


ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: chat-bot-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix


hpa:
  enable: false