name: chat-bot
imagename: chat-bot
namespace: bbsoft
service:
  type: ClusterIP
  port: 8080
deployment:
  replica: 1
  livenessProbe: true
  readinessProbe: true
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral_storage: 512Mi
    limits:
      cpu: "500m"
      ephemeral_storage: 1Gi
      memory: 1Gi
  restartPolicy: Always
  env:
    SECURITY_CORS_ORIGINS: '*, https://game-api-dev.bbsoft.by, https://apigateway-dev.bbsoft.by, https://static-dev.bbsoft.by'
    NEXT_PUBLIC_API_URL: https://apigateway-dev.bbsoft.by/
    NEXT_PUBLIC_STAGE_API_TOLOTO_URL: https://stage-api.toloto.by
    NEXT_PUBLIC_STAGE_ACTIVE_LOTTERY_API_URL: https://stage-active-lottery.toloto.by
ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: real_ip_header X-Forwarded-For; real_ip_recursive on;
  hosts:
  - host: apigateway-preprod.bbsoft.by
    paths:
      - path: /
        pathType: Prefix
hpa:
  enable: false