name: analytics
imagename: analytics
namespace: default


service:
  type: ClusterIP
  multiport: 
  - name: analytics
    port: 8080


deployment:
  replicas: 1
  imagePullSecrets:
    - gcr-json-key
  containers:
  - name: analytics
    imagename: analytics
    port: 8080
    probe:
      livenessProbe:
        enable: true
        initialDelaySeconds: 120
        probeType: http
        http:
          path: /actuator/health
          port: 8080
      readinessProbe:
        enable: true
        initialDelaySeconds: 10
        probeType: http
        http:
          path: /actuator/health
          port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
    restartPolicy: Always
    env: {}
    envFromSecret:
      JWT_KEY:
        jwt-qa: jwt-key
      BIGQUERY_PRIVATE-KEY:
        bigquery-secret: bigquery-key

ingress:
  enable: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: mytestingress
    paths:
      - path: /
        pathType: Prefix
  tls:
  - hosts:
    - mytestingress
    secretName: default-ssl-secret

hpa:
  enable: false